{% set version = "9.10.2.21" %}
{% set build_number = "0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]


package:
  name: cudnn
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/{{ platform }}/cudnn-{{ platform }}-{{ version }}_cuda{{ cuda_maj_version }}-archive.{{ extension }}
  sha256: ab05bc70a120425b8b811544a6bc6458ca1f3cc54a8ccc51a1113749ecab1442  # [linux64 and (cuda_maj_version == 11)]
  sha256: d0defcbc4c6dad711ff4cb66d254036a300c9071b07c7b64199aacab534313c1  # [linux64 and (cuda_maj_version == 12)]
  sha256: 6461e6037a3b8ab5a9c17f527877d493f7cde9eb855fadf686140c7e3fb41aaf  # [aarch64 and (cuda_maj_version == 11)]
  sha256: 4d57dceba3be27a68b078ce8630525bf40ab7f1b546eb45d0b363c3eeb55f8fa  # [aarch64 and (cuda_maj_version == 12)]
  sha256: dc837ef00beffab937979ba5a72c27facd0443c7e3fa71fc7c2e29adf5262f36  # [win and (cuda_maj_version == 11)]
  sha256: c1a4567d822ebda7373fa1f19255dff4942302de741f830160b6c7d1fb31af23  # [win and (cuda_maj_version == 12)]

build:
  skip: True  # [osx]
  number: {{ build_number }}
  string: cuda{{ cuda_maj_version }}_{{ build_number }}
  missing_dso_whitelist:
    - '*'
  run_exports:
    - {{ pin_subpackage('cudnn', min_pin='x.x', max_pin='x') }}

requirements:
  run:
    - cudatoolkit {{ cuda_maj_version }}.*   # [cuda_maj_version == 11]
    - cuda-version {{ cuda_maj_version }}.*
    - cuda-nvrtc                             # [cuda_maj_version == 12]
    - libcublas                              # [cuda_maj_version == 12]
    # libcudnn_cnn_infer.so needs libm.so.6 with ABI v2.27, shown when test_load_elf is run. So we include this __glibc
    # restriction. This means, though, that we can't install cudnn in our linux-aarch64 builder containers (which have
    # glibc v2.26), including to run the tests while building the package. However, we don't currently build anything for
    # linux-aarch64 CUDA - and when we start, a solver error will flag up this issue to be handled appropriately at that
    # time.
    - __glibc >=2.27                         # [linux and aarch64]

test:
  requires:
    - {{ compiler('c') }}                                                                                        # [linux and x86_64]
  files:
    - test_load_elf.c                                                                                            # [linux and x86_64]
  commands:
    - if not exist %LIBRARY_INC%\\cudnn.h exit 1                                                                 # [win]
    - if not exist %LIBRARY_INC%\\cudnn_adv.h exit 1                                                             # [win]
    - if not exist %LIBRARY_LIB%\\cudnn.lib exit 1                                                               # [win]
    - if not exist %LIBRARY_LIB%\\cudnn64_{{ '.'.join(version.split('.')[0:1]) }}.lib exit 1               # [win]
    - if not exist %LIBRARY_LIB%\\cudnn_adv.lib exit 1                                                           # [win]
    - if not exist %LIBRARY_LIB%\\cudnn_adv64_{{ '.'.join(version.split('.')[0:1]) }}.lib exit 1           # [win]
    - if not exist %LIBRARY_BIN%\\cudnn64_{{ '.'.join(version.split('.')[0:1]) }}.dll exit 1               # [win]
    - if not exist %LIBRARY_BIN%\\cudnn_adv64_{{ '.'.join(version.split('.')[0:1]) }}.dll exit 1           # [win]
    - test -f ${PREFIX}/include/cudnn.h                                                                          # [linux and x86_64]
    - test -f ${PREFIX}/include/cudnn_adv.h                                                                      # [linux and x86_64]
    - test -f ${PREFIX}/lib/libcudnn.so                                                                          # [linux and x86_64]
    - test -f ${PREFIX}/lib/libcudnn_adv.so                                                                      # [linux and x86_64]
    - test -f ${PREFIX}/lib/libcudnn.so.{{ '.'.join(version.split('.')[0:1]) }}                            # [linux and x86_64]
    - test -f ${PREFIX}/lib/libcudnn.so.{{ '.'.join(version.split('.')[0:3]) }}                            # [linux and x86_64]
    - ${GCC} test_load_elf.c -std=c99 -Werror -ldl -o test_load_elf                                              # [linux and x86_64]
    - for f in ${PREFIX}/lib/libcudnn*.so; do ./test_load_elf $f; done                                           # [linux and x86_64]

about:
  home: https://developer.nvidia.com/cudnn
  license_file: LICENSE
  license_family: PROPRIETARY
  license: LicenseRef-Proprietary
  summary: "NVIDIA's cuDNN deep neural network acceleration library"
  description: |
    The NVIDIA CUDA® Deep Neural Network library (cuDNN) is a GPU-accelerated library of primitives for deep neural
    networks. cuDNN provides highly tuned implementations for standard routines such as forward and backward
    convolution, pooling, normalization, and activation layers.
  doc_url: https://docs.nvidia.com/deeplearning/cudnn
  dev_url: https://developer.nvidia.com/rdp/cudnn-download
